---
- name: Check if systemd exists
  stat: path=/etc/systemd/system
  register: systemd_check

- name: Install nsqadmin systemd service
  template:
    src: nsqadmin.service.j2
    dest: /etc/systemd/system/nsqadmin.service
  when: systemd_check.stat.exists == true
  notify:
    - reload daemon
    - restart nsqadmin
